services:
  expensify-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expensify-api
    environment:
      DB_HOST: expensify-db
      DB_PORT: 5432
      DB_NAME: expensify
      DB_USERNAME: dummy_user
      DB_PASSWORD: dummy_password
      JWT_SECRET: zWc8nQOVADdplXUcg/ZtXgBZRq9SZY62sAFtnUDOEbg=
    depends_on:
      - expensify-db
    ports:
      - "8080:8080"
    networks:
      - expensify-network

  expensify-db:
    image: postgres:13
    container_name: expensify-db
    environment:
      POSTGRES_USER: dummy_user
      POSTGRES_PASSWORD: dummy_password
      POSTGRES_DB: expensify
    ports:
      - "5432:5432"
    volumes:
      - expensify-db-data:/var/lib/postgresql/data
    networks:
      - expensify-network

volumes:
  expensify-db-data:

networks:
  expensify-network:
    external: true